# Site settings
title: gi stardust
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here are the building blocks to a successful front-end development world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://getinsured.github.io/dev/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal